url: http://mishochu.com
name: Mish Ochu
email: mishochu@gmail.com
github: mishfit
twitter: notapplicable
markdown: redcarpet
pygments: true

# Google Analytics
google_analytics_tracking_id: UA-48627216-1
