#
# Blog Settings
#
author: Mish Ochu
description: still thinking...
url: http://mishochu.com
title: Mish Ochu
subtitle: just wait, he's thinking
gravatar_url: http://www.gravatar.com/avatar/47d3b3db28b9a5cd3adbaf52f924099c.png
name: Mish Ochu
email: mishochu@gmail.com

# Github repositories
github_user: mishfit
github_repo_url: https://github.com/mishfit/mishfit.github.io/

# Twitter
twitter_user: mishochu
twitter_tweet_button: true

# Disqus Comments
disqus_short_name: mishochu
disqus_show_comment_count: true

# Google Analytics
google_analytics_tracking_id: UA-48627216-1
#
# Jekyll Settings
#
markdown: kramdown
permalink: /archive/:year/:month/:day/:title/
paginate: 20
paginate_path: "page/:num"
category_dir: categories

gems:
  - jekyll-redirect-from
  - jekyll-sitemap
